project:
  type: website
  output-dir: docs
  resources: data/*.csv

website:
  title: "Machine Learning"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Inicio"
        href: index.qmd
      - section: "Natural Language Processing (NLP)"
        contents:
          - LABORATORIO_2.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    fig-align: center